services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    volumes:
      - ./backend:/var/www/html
    ports:
      - "8081:8081"
    depends_on:
      - db
    command: sh ./docker-entrypoint.sh

  db:
    image: mysql:5.7
    container_name: db
    environment:
      MYSQL_DATABASE: takehome
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    volumes:
      - ./frontend:/app
    ports:
      - "8000:8080"
    depends_on:
      - backend

volumes:
  db_data:
